version: '3.9'

services:
  database:
    container_name: sqlite3_container
    image: sqlite:latest
    volumes:
      - /app

  webapi:
    container_name: webapi_container
    image: webapi
    ports:
      - "8080:5000"
    volumes:
      - /app
    depends_on:
      - database
    restart: unless-stopped

  tests:
    container_name: tests_container
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: 0